version: '3'
services:
  data-pipeline-db:
    image: data-pipeline-db
    restart: always
    container_name: data-pipeline-db
    shm_size: 512mb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
