version: '3.4'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5000:8080"
      - "5001:5001"
    depends_on:
      - db
  db:
    container_name: db
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "CJnEmigeG!@JLipcRy4&2MNv"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
