version: '3.8'
services:
  landing:
    image: landing
    container_name: landing
    build:
      context: .
      dockerfile: ./apps/landing/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
