version: '3.8'

services:
 db:
    container_name: db-klv
    image: mysql:8.0.30
    restart: always
    volumes:
    - .db-data:/var/lib/mysql
    - ./docker/mysql-config/my.cnf:/etc/mysql/my.cnf
    - ./docker/mysql-init-scripts/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: Std@12345678
      MYSQL_USER: UKlv
      MYSQL_PASSWORD: UKlv@2024
