version: '3.9'

services:
  web:
    build: .
    container_name: web
    restart: unless-stopped
    ports:
      - '8000:8000'

  database:
    image: postgres:16
    environment:
      - POSTGRES_DB=movies_database
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
