version: "3.8"
services:
  postgres:
    image: postgres:16.2
    container_name: postgresdb
    networks:
      - compose-shop
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  client:
    image: postgres:16.2
    container_name: client
    networks:
      - compose-shop
    environment:
      - PGPASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "psql -h postgres -U postgres -c 'SELECT * from pg_user;'"

networks:
  compose-shop:
    driver: bridge
