# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
    - id: bandit
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    -   id: python-safety-dependencies-check
      # -   repo: https://github.com/awslabs/git-secrets
      # rev: 1.3.0
      # hooks:
      # -   id: git-secrets
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
      #        args: ['--baseline', '.secrets.baseline']
      # exclude: package.lock.json
