version: '3'
services:
  api:
    image: pr-auto-remediation-api
    build:
      context: .
    volumes:
      - ./app:/usr/src/app
  db:
    image: postgres:latest
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
