version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=taskmanagerdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    logging:
      driver: "none"

  server:
    container_name: server
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=db
