version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
  db:
    image: mysql:innovation-oracle
    environment:
      MYSQL_DATABASE: wordle
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
