version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_BASE_URL=http://backend:80
    restart: always
    ports:
      - 80:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:80
