version: "3.9"

services:
  php:
    build:
      context: .
      target: php
      args:
          - APP_ENV="${APP_ENV}"
    environment:
      - APP_ENV="${APP_ENV}"
      - CONTAINER_ROLE=app
      - MYSQL_PWD=${DB_PASSWORD}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.2
    ports:
      -   3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
    db-data: ~
