version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "7113:80"
      - "7114:443"
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certificates:/etc/ssl/certs/self-signed
    networks:
      - default

  api:
    container_name: api
    build:
      context: .
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
