version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - stack

  api:
    container_name: api
    build:
      context: .
    networks:
      - stack

networks:
  stack:
