version: '3.8'

services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - flask

  flask:
    container_name: flask
    image: flask:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 "app:app"

  test:
    image: flask:latest
    container_name: test
    depends_on:
      - nginx
    command: python3 test.py
