volumes:
  node_modules:
services:
  frontend:
    container_name: frontend
    working_dir: /app
    # restart: always
    build: .
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app/src
      # - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
