version: '3.8'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - data-wp:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
  db:
    image: mysql:5.7
    volumes:
      - data-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
volumes:
  data-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage/data-db
  data-wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage/data-wp
