version: '3'

services:
  traefik:
    image: traefik:v2.11
    container_name: "traefik"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik_web"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http.tls.certResolver=le"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=your@email.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: "gitlab.example.com"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'https://gitlab.example.com'"
    networks:
      - traefik_web
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`gitlab.example.com`)
      - traefik.http.routers.gitlab.entrypoints=https
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.services.gitlab.loadbalancer.server.port=80

networks:
  traefik_web:
    name: traefik_web
