version: '3'

services:
  jupyter:
    build:
      context: ..
      dockerfile: ./jupyter-r/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/app/notebooks  # Mount a local folder to store notebooks
    environment:
      - TZ=UTC+1  # Set the container timezone
    image: jupyter_r
    container_name: jupyter_r

