version: '3.8'

services:
  hadoop:
    build: ./hadoop  # Replace with your actual Hadoop Dockerfile path
    container_name: hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8042:8042"
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    restart: on-failure
    logging:
      driver: none

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: hive
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
    ports:
      - "5432:5432"
    # 🚨 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  hive:
    build: ./hive  # Assumes you have a Dockerfile in the ./hive directory
    container_name: hive
    #env_file: ./hive/hive.env  # Reference to the environment file
    environment:
      POSTGRES_JDBC_VERSION: 42.2.24
      POSTGRES_HOST: postgres  # Ensure PostgreSQL host is set
      POSTGRES_DB: hive
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
    depends_on:
      postgres:
        condition: service_healthy
      hadoop:
        condition: service_started
    ports:
      - "10000:10000"
      - "10002:10002"