services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.17
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_BASEPATH: /whatever
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_USERNAME: user
      ELASTICSEARCH_PASSWORD: password
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

networks:
  elastic:
    name: elastic-network
