version: "3.9"

# services:
#   mongodb:
#     image: mongo:7.0.7
#     restart: always
#     volumes:
#       - ./scripts/mongodb/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
#     ports:
#       - 27017:27017
#     # environment:
#     #   MONGO_INITDB_ROOT_USERNAME: root
#     #   MONGO_INITDB_ROOT_PASSWORD: test
#     command: ["--replSet", "dbrs", "--bind_ip", "0.0.0.0"]

# services:

#   mongodb:
#     image: mongo
#     hostname: mongodb
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: password
#     command: ["--replSet", "dbrs", "--bind_ip", "0.0.0.0"]
#     volumes:
#       - ./scripts/mongodb/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js

#   mongo-express:
#     image: mongo-express
#     restart: always
#     depends_on:
#       - mongodb
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: password
#       ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/

services:
  mongo:
    image: mongo:7.0.7
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongo-init-rset.sh:/mongo-init-rset.sh
      # - ./scripts/mongodb/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
    command: ./mongo-init-rset.sh

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
    - mongo
    ports:
        - ${MONGOEXP_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
