version: "3.9"

services:
  mongodb:
    image: mongo:7.0.7
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./scripts/rs-initiate.sh:/rs-initiate.sh
    command: ./rs-initiate.sh

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
    - mongodb
    ports:
        - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
