services:
  app-node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql2
    environment:
      DB_HOST: mysql2
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      mysql2:
        condition: service_healthy

  mysql2:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pcontra31"]
      interval: 1s
      retries: 120
