version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gotodo
    ports:
      - "3306:3306"

  go-todo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_DATABASE: gotodo
