version: "3"
services:
  spring-boot-app:
    container_name: spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    image: imageone
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
