version: '3.8'

services:
  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 1s
      retries: 120

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    links:
      - db:db
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
