version: "3.9"

services:
    redis:
        image: 'bitnami/redis:7.2.4'
        container_name: 'redis'
        environment:
            - REDIS_PASSWORD=4iauxFqoQPqCwA%G
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis-core-data:/bitnami/redis/data

volumes:
    redis-core-data:
        driver: local
