version: '3.8'

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ Management UI
      - "5552:5552"  # Streams
    logging:
      driver: none

  dotnetapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
