version: '3.7'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    # ports:
    #   - "80:80"

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
