version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - directus
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - stack

  directus:
    container_name: directus
    image: directus/directus:10.8.3
    volumes:
      - ./extensions:/directus/extensions
    environment:     
      PUBLIC_URL: "http://localhost:8055"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
    networks:
      - stack

networks:
  stack:
