version: '3'
services:
  ubuntu_anaconda:
    image: continuumio/anaconda3:latest
    container_name: ubuntu_anaconda
    environment:
      - JUPYTER_TOKEN=my_secret_token
    # command: /bin/bash -c "/opt/conda/bin/conda install -y -c conda-forge pystan && /opt/conda/bin/jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=${JUPYTER_TOKEN}"
    command: /bin/bash -c "echo ${JUPYTER_TOKEN}"
