version: '3.8'

services:
  wordpress:
    container_name: wordpress
    build:
      context: .
      target: build
    volumes:
      - wordpress-data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: .
      target: nginx-server
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - app-network

  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - app-network

volumes:
  wordpress-data:
  db-data:

networks:
  app-network:
    driver: bridge
