version: '3.1'
services:
  redis:
    image: redis:latest
    restart: always
    container_name: cache
    ports:
     - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass pirate
    logging:
      driver: "none"
  worker:
    image: worker
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=pirate
