version: "3.7"
services:
  mysql:
    image: mysql:5.6.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: roots
      MYSQL_DATABASE: oks
  api_service:
    build: ./oks-api
    ports:
      - 8081:8081
    depends_on:
      - mysql
    environment:
      spring.datasource.url: jdbc:mysql://mysql/oks?characterEncoding=UTF-8
      spring.datasource.username: root
      spring.datasource.password: roots
