version: '3.7'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ="Europe/Madrid"
    ports:
      - "8123:8123"
    volumes:
      - ./config/:/config
