version: "3.5"

services:
  Database:
    image: postgres
    container_name: Example-Production-Database
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U ${DATABASE_USER_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    image: postgres
    environment:
      - PGPASSWORD=${DATABASE_PASSWORD}
    command: sh -c "psql -h Database -U ${DATABASE_USER_NAME} -c 'SELECT * from pg_user;'"
    depends_on:
      Database:
        condition: service_healthy
