version: '3'
services:
  data-pipeline-db:
    image: data-pipeline-db
    restart: always
    shm_size: 512mb
    build:
      context: .
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=data-pipeline
      - POSTGRES_PASSWORD=test
