version: '3.8'

services:
  php:
    image: php:5.6-apache
    volumes:
      - ./custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
      - .:/mnt
    command: /bin/bash -c "/usr/local/bin/custom-entrypoint.sh"
