version: '3.7'

services:
  docker-mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  myapp:
    image: mysql:latest
    container_name: myapp
    depends_on:
      docker-mysql:
        condition: service_healthy
    command: mysql -h docker-mysql -u root -p'root' -e 'SHOW DATABASES;'
