version: '3.1'
services:
  odoo_v2:
    image: odoo:17
    depends_on:
      - db_v2
    environment:
      - HOST=db_v2
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - 8069:8069

  db_v2:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - odoo_v2

volumes:
  odoo-web-data:
