version: '3.8'

services:
  apache:
    container_name: apache
    image: httpd:2.4
    ports:
      - "8080:8080"
    volumes:
      - ./Services/Apache/apache.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - django

  django:
    container_name: django
    build:
      context: Services/Chronocommand
    ports:
      - "8000:8000"
    volumes:
      - ./Services/Chronocommand:/src
    command: python manage.py runserver 0.0.0.0:8000

# #   traefik:
# #     image: "traefik:v3.0"
# #     ports:
# #       - "80:80"
# #       - "443:443"
# #       - "8888:8080"  # Traefik dashboard
# #     networks:
# #       - proxy
# #     volumes:
# #       - /var/run/docker.sock:/var/run/docker.sock
# #       - ./Services/DevTraefik/:/etc/traefik

# # networks:
# #   proxy:
# #     external: true
