version: '3.8'

services:
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs
#   # web:
#   #   depends_on:
#   #     - django
#   #     - traefik
#   #   expose:
#   #     - "${VIRTUAL_PORT}"
#   #   networks:
#   #     - default
#   #     - proxy
#   #   labels:
#   #     - "traefik.enable=true"
#   #     - "traefik.http.routers.chronocommand.rule=Host(`localhost`)"
#   #     - "traefik.docker.network=proxy"
#   #     - "traefik.http.routers.chronocommand.entrypoints=web,websecure"

#   web:
#     container_name: web
#     image: httpd:2.4
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./Services/Apache/apache.conf:/usr/local/apache2/conf/httpd.conf
#     depends_on:
#       - django
#     command: sleep 600

#   django:
#     container_name: django
#     build:
#       context: Services/Chronocommand
#     # expose:
#     #   - "80"
#     ports:
#     #   - "8080:80"
#       - "8000:8000"
#     #   - "3000:3000"
#     volumes:
#       - ./Services/Chronocommand:/src
#     command: python manage.py runserver 0.0.0.0:8000

# #   traefik:
# #     image: "traefik:v3.0"
# #     ports:
# #       - "80:80"
# #       - "443:443"
# #       - "8888:8080"  # Traefik dashboard
# #     networks:
# #       - proxy
# #     volumes:
# #       - /var/run/docker.sock:/var/run/docker.sock
# #       - ./Services/DevTraefik/:/etc/traefik

# # networks:
# #   proxy:
# #     external: true
